engines:
    radon:
        enabled: true
        exclude_paths:
            - "*/tests/"  # many asserts mean high McCabe
        config:
            threshold: "C"

    fixme:
        enabled: true
        issue_override:
            severity: info
        exclude_paths:
            - "**pdb"

    duplication:
        enabled: true
        checks:
            Similar code:
                enabled: true
                issue_override:
                    severity: info
        config:
            languages:
                python:
                    mass_threshold: 35

file-lines:
    config:
        threshold: 750  # 1000 is really the hard edge
        # Note that this counts *all* lines, not logical lines. So including
        # good documentation counts against the default 250-line limit!

exclude_paths:
    - "docs/"

ratings:
    paths:
        - "**py"
