engines:
    radon:
        enabled: true
        exclude_paths:
            - "*/tests/"

    fixme:
        enabled: true
        exclude_paths:
            - "**pdb"

    duplication:
        enabled: true

ratings:
    paths:
        - "**py"
