engines:
    radon:
        enabled: true
        exclude_paths:
            - "*/tests/"
        config:
            threshold: "C"

    fixme:
        enabled: true
        exclude_paths:
            - "**pdb"

    duplication:
        enabled: true
        languages:
            python:
                mass_threshold: 35

ratings:
    paths:
        - "**py"
