language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    #- "3.7-dev"  # need to do custom requirements install for this

install:
    - source ci/pip-install/install.sh
    - pip install -r ci/pip-install/testing_requirements.txt

script:
    - py.test -vv --cov=contact_map

after_success:
    - coveralls

