language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
    - source ci/pip-install/install.sh
    - pip install -r ci/pip-install/test_requirements.txt

script:
    - export PYTEST="pytest"
    - if ! [ -x "$(command -v pytest)" ]; then export PYTEST="py.test"; fi
    - py.test -vv --cov=contact_map
