# See also:
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

branches:
  only:
    - master
    - stable

max_jobs: 4

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run_with_env.cmd"
    PYTHONUNBUFFERED: 1

  matrix:
    - PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"
      ARCH: '32'
    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      ARCH: '64'
    - PYTHON: "C:\\Miniconda37"
      CONDA_PY: "37"
      ARCH: '32'
    - PYTHON: "C:\\Miniconda37-x64"
      CONDA_PY: "37"
      ARCH: '64'

build: false

install:
  # install python
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  # test python version
  - "%CMD_IN_ENV% conda config --add channels omnia"  # TODO: switch to conda-forge?
  - "%CMD_IN_ENV% conda update -yq --all"
  - "%CMD_IN_ENV% conda install -yq \"conda-build<3.0.26\""
  - "%CMD_IN_ENV% python --version"
  - "%CMD_IN_ENV% python -c \"import struct; print(struct.calcsize('P') * 8)\""
  # now we do our own install

test_script:
  - "%CMD_IN_ENV% conda build --quiet ci\\conda-recipe"
